// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'sleep_record.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7154496104564186480),
      name: 'SleepRecord',
      lastPropertyId: const IdUid(8, 2266601415029794558),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 587096047532968569),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7668392535524400172),
            name: 'timeForBed',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6056668378679045481),
            name: 'wakeUpTime',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2298693736245816715),
            name: 'sleepTime',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 2864271183918240577),
            name: 'numberOfAwaking',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 7623539963839053198),
            name: 'timeOfAwaking',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 6730085741061181353),
            name: 'morningFeeling',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 2266601415029794558),
            name: 'qualityOfSleep',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 7154496104564186480),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    SleepRecord: EntityDefinition<SleepRecord>(
        model: _entities[0],
        toOneRelations: (SleepRecord object) => [],
        toManyRelations: (SleepRecord object) => {},
        getId: (SleepRecord object) => object.id,
        setId: (SleepRecord object, int id) {
          object.id = id;
        },
        objectToFB: (SleepRecord object, fb.Builder fbb) {
          final timeForBedOffset = fbb.writeString(object.timeForBed);
          final wakeUpTimeOffset = fbb.writeString(object.wakeUpTime);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, timeForBedOffset);
          fbb.addOffset(2, wakeUpTimeOffset);
          fbb.addInt64(3, object.sleepTime);
          fbb.addInt64(4, object.numberOfAwaking);
          fbb.addInt64(5, object.timeOfAwaking);
          fbb.addInt64(6, object.morningFeeling);
          fbb.addInt64(7, object.qualityOfSleep);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final timeForBedParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final wakeUpTimeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final sleepTimeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final numberOfAwakingParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final timeOfAwakingParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final morningFeelingParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final qualityOfSleepParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final object = SleepRecord(
              timeForBed: timeForBedParam,
              wakeUpTime: wakeUpTimeParam,
              sleepTime: sleepTimeParam,
              numberOfAwaking: numberOfAwakingParam,
              timeOfAwaking: timeOfAwakingParam,
              morningFeeling: morningFeelingParam,
              qualityOfSleep: qualityOfSleepParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [SleepRecord] entity fields to define ObjectBox queries.
class SleepRecord_ {
  /// see [SleepRecord.id]
  static final id =
      QueryIntegerProperty<SleepRecord>(_entities[0].properties[0]);

  /// see [SleepRecord.timeForBed]
  static final timeForBed =
      QueryStringProperty<SleepRecord>(_entities[0].properties[1]);

  /// see [SleepRecord.wakeUpTime]
  static final wakeUpTime =
      QueryStringProperty<SleepRecord>(_entities[0].properties[2]);

  /// see [SleepRecord.sleepTime]
  static final sleepTime =
      QueryIntegerProperty<SleepRecord>(_entities[0].properties[3]);

  /// see [SleepRecord.numberOfAwaking]
  static final numberOfAwaking =
      QueryIntegerProperty<SleepRecord>(_entities[0].properties[4]);

  /// see [SleepRecord.timeOfAwaking]
  static final timeOfAwaking =
      QueryIntegerProperty<SleepRecord>(_entities[0].properties[5]);

  /// see [SleepRecord.morningFeeling]
  static final morningFeeling =
      QueryIntegerProperty<SleepRecord>(_entities[0].properties[6]);

  /// see [SleepRecord.qualityOfSleep]
  static final qualityOfSleep =
      QueryIntegerProperty<SleepRecord>(_entities[0].properties[7]);
}
